import '../styles/globals.css'
import Head from 'next/head';

// import { AppProvider } from '../providers/AppContext';

function MyApp({ Component, pageProps }) {
  return (
    // <AppProvider>
    <>
      <Head>
        <title>Textiu | A plataforma que reúne profissionais do setor têxtil à melhores oportunidades do mercado.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <Component {...pageProps} />
    </>
    // </AppProvider>
    )
}

export default MyApp
